-- ============================================================
-- Top Note — Curated catalog top-up (Parfumo, free-tier source)
-- ============================================================
-- WHAT: adds 30 net-new, well-rated fragrances from recognizable
--       houses, taking the live catalog from 185 toward the ~200 target.
--       This is a CURATED top-up, not a bulk dump — the catalog is
--       intentionally kept editorial and quiet-luxury.
--
-- SOURCE: Parfumo (rfordatascience/tidytuesday, 2024-12-10).
--   Generated by scripts/import-parfumo-catalog.ts (see scripts/README.md).
--
-- LICENSING: Parfumo data is used here ONLY as a non-commercial / free-tier
--   demo source. It must be replaced with a licensed source (e.g. FragDB) or
--   first-party/affiliate data before any commercial launch. See art_xzsw1Igb.
--
-- SCHEMA: Option A — NO schema changes. Every value targets an existing
--   `fragrances` column. Provenance (source + upstream id) lives in the
--   manifest comments below, NOT in any DB column. avg_rating is rescaled
--   from Parfumo’s 0–10 to TopNote’s 0–5; review_count is the rating count.
--   attributes/seasons are intentionally empty: the dataset carries no
--   longevity/sillage/price/season data and nothing is fabricated. New rows
--   have bottle_image_url = NULL (the UI falls back to an initial tile).
--
-- HOW TO RUN: paste this file into the Supabase Dashboard → SQL Editor and run.
--   It is ADDITIVE and IDEMPOTENT — every row is guarded by NOT EXISTS on
--   lower(name)+lower(house), so re-running inserts nothing new and never
--   duplicates. No migration is required; the file is inert until run.
--
-- HOUSES (20): Acqua di Parma, Al Haramain, Amouage, Bvlgari, Chanel, Creed, Dior, Dolce & Gabbana, Giorgio Armani, Guerlain, Issey Miyake, Kilian, Parfums de Marly, Prada, Rasasi, Tom Ford, Valentino, Versace, Xerjoff, Yves Saint Laurent
--
-- MANIFEST (provenance for each added row):
--     1. Issey Miyake — L'Eau d'Issey pour Homme  [designer / Fresh / ★3.8 · 1471 ratings]  (https://www.parfumo.com/Perfumes/Issey_Miyake/L_Eau_d_Issey_pour_Homme_Eau_de_Toilette)
--     2. Giorgio Armani — Emporio Armani - Stronger With You  [designer / Sweet / ★3.7 · 1376 ratings]  (https://www.parfumo.com/Perfumes/Giorgio_Armani/Emporio_Armani_Stronger_With_You)
--     3. Giorgio Armani — Armani Code Black Code  [designer / Spicy / ★3.8 · 1350 ratings]  (https://www.parfumo.com/Perfumes/Giorgio_Armani/Armani_Code_Black_Code_Eau_de_Toilette)
--     4. Versace — Blue Jeans  [designer / Fresh / ★3.5 · 1243 ratings]  (https://www.parfumo.com/Perfumes/Versace/Blue_Jeans)
--     5. Dolce & Gabbana — The One for Men  [designer / Spicy / ★3.9 · 1212 ratings]  (https://www.parfumo.com/Perfumes/Dolce_Gabbana/The_One_for_Men)
--     6. Parfums de Marly — Kalan  [niche / Spicy / ★3.7 · 1208 ratings]  (https://www.parfumo.com/Perfumes/Parfums_de_Marly/kalan)
--     7. Amouage — Sunshine Man  [niche / Sweet / ★4 · 1149 ratings]  (https://www.parfumo.com/Perfumes/Amouage/Sunshine_Man)
--     8. Bvlgari — Aqva Amara  [designer / Aquatic / ★3.9 · 1117 ratings]  (https://www.parfumo.com/Perfumes/Bvlgari/aqva-amara-eau-de-toilette)
--     9. Yves Saint Laurent — Kouros  [designer / Musky / ★3.6 · 1105 ratings]  (https://www.parfumo.com/Perfumes/Yves_Saint_Laurent/Kouros_Eau_de_Toilette)
--    10. Parfums de Marly — Greenley  [niche / Fresh / ★4 · 1095 ratings]  (https://www.parfumo.com/Perfumes/Parfums_de_Marly/greenley)
--    11. Kilian — Back to Black, Aphrodisiac  [niche / Sweet / ★3.9 · 1072 ratings]  (https://www.parfumo.com/Perfumes/Kilian/back-to-black-aphrodisiac-perfume)
--    12. Versace — Versace Man Eau Fraîche  [designer / Fresh / ★3.8 · 1064 ratings]  (https://www.parfumo.com/Perfumes/Versace/Versace_Man_Eau_Fraiche_Eau_de_Toilette)
--    13. Tom Ford — Grey Vetiver  [designer / Fresh / ★4 · 1047 ratings]  (https://www.parfumo.com/Perfumes/Tom_Ford/Grey_Vetiver)
--    14. Prada — Amber pour Homme  [designer / Powdery / ★4 · 1007 ratings]  (https://www.parfumo.com/Perfumes/Prada/Amber_pour_Homme_Eau_de_Toilette)
--    15. Xerjoff — Casamorati - Dolce Amalfi  [niche / Fruity / ★4 · 1004 ratings]  (https://www.parfumo.com/Perfumes/Xerjoff/Casamorati__Dolce_Amalfi)
--    16. Guerlain — Santal Royal  [designer / Woody / ★4 · 994 ratings]  (https://www.parfumo.com/Perfumes/Guerlain/Santal_Royal)
--    17. Creed — Himalaya  [niche / Fresh / ★3.9 · 971 ratings]  (https://www.parfumo.com/Perfumes/Creed/Himalaya)
--    18. Xerjoff — Casamorati - Mefisto  [niche / Citrus / ★4 · 956 ratings]  (https://www.parfumo.com/Perfumes/Xerjoff/Casamorati_1888_Mefisto)
--    19. Chanel — Allure Homme  [designer / Woody / ★4 · 934 ratings]  (https://www.parfumo.com/Perfumes/Chanel/Allure_Homme)
--    20. Acqua di Parma — Bergamotto di Calabria  [designer / Citrus / ★4 · 931 ratings]  (https://www.parfumo.com/Perfumes/Acqua_di_Parma/bergamotto-di-calabria)
--    21. Yves Saint Laurent — M7 Oud Absolu  [designer / Woody / ★4 · 925 ratings]  (https://www.parfumo.com/Perfumes/Yves_Saint_Laurent/m7-2011-m7-oud-absolu)
--    22. Acqua di Parma — Mandorlo di Sicilia  [designer / Sweet / ★3.8 · 912 ratings]  (https://www.parfumo.com/Perfumes/Acqua_di_Parma/mandorlo-di-sicilia)
--    23. Valentino — Valentino Uomo  [designer / Sweet / ★4 · 876 ratings]  (https://www.parfumo.com/Perfumes/Valentino/valentino-uomo-2014-eau-de-toilette)
--    24. Rasasi — Daarej pour Homme  [middle-eastern / Sweet / ★3.8 · 873 ratings]  (https://www.parfumo.com/Perfumes/Rasasi/Daarej_pour_Homme)
--    25. Creed — Original Vetiver  [niche / Fresh / ★4 · 860 ratings]  (https://www.parfumo.com/Perfumes/Creed/Original_Vetiver)
--    26. Guerlain — L'Homme Idéal  [designer / Sweet / ★3.7 · 852 ratings]  (https://www.parfumo.com/Perfumes/Guerlain/L_homme_ideal)
--    27. Dolce & Gabbana — Light Blue pour Homme Forever  [designer / Citrus / ★4 · 849 ratings]  (https://www.parfumo.com/Perfumes/Dolce_Gabbana/light-blue-pour-homme-forever)
--    28. Dior — Eau Sauvage Parfum  [designer / Citrus / ★4.2 · 830 ratings]  (https://www.parfumo.com/Perfumes/Dior/Eau_Sauvage_Parfum_2017)
--    29. Al Haramain — L'Aventure  [middle-eastern / Citrus / ★4 · 819 ratings]  (https://www.parfumo.com/Perfumes/Al_Haramain/L_Aventure)
--    30. Amouage — Lyric Man  [niche / Floral / ★3.9 · 807 ratings]  (https://www.parfumo.com/Perfumes/Amouage/Lyric_Man)
-- ============================================================

WITH seed (id, house, name, type, category, scent_family, top_notes, heart_notes, base_notes, attributes, seasons, avg_rating, review_count, bottle_image_url) AS (
  VALUES
    ('issey-miyake-l-eau-d-issey-pour-homme', 'Issey Miyake', 'L''Eau d''Issey pour Homme', 'Fresh Citrus', 'designer', 'Fresh', ARRAY['Yuzu','Mandarin orange']::text[], ARRAY['Nutmeg','Water lily','Cinnamon']::text[], ARRAY['Sandalwood','Vetiver','Amber','Tobacco']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.8, 1471, NULL),
    ('giorgio-armani-emporio-armani-stronger-with-you', 'Giorgio Armani', 'Emporio Armani - Stronger With You', 'Sweet Spicy', 'designer', 'Sweet', ARRAY['Cardamom','Pink pepper','Violet leaf']::text[], ARRAY['Sage']::text[], ARRAY['Vanilla','Marron glacé']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.7, 1376, NULL),
    ('giorgio-armani-armani-code-black-code', 'Giorgio Armani', 'Armani Code Black Code', 'Spicy Sweet', 'designer', 'Spicy', ARRAY['Bergamot','Lemon']::text[], ARRAY['Star anise','Olive blossom']::text[], ARRAY['Tonka bean','Gaiac wood','Leather','Tobacco']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.8, 1350, NULL),
    ('versace-blue-jeans', 'Versace', 'Blue Jeans', 'Fresh Citrus', 'designer', 'Fresh', ARRAY['Citrus fruits','Aniseed','Bergamot','Rosewood','Basil','Juniper']::text[], ARRAY['Heliotrope','Lavender','Carnation','Jasmine','Sage','Fir','Geranium','Lily of the valley','Rose']::text[], ARRAY['Tonka bean','Amber','Cedar','Iris','Musk','Patchouli','Sandalwood','Vanilla','Vetiver']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.5, 1243, NULL),
    ('dolce-gabbana-the-one-for-men', 'Dolce & Gabbana', 'The One for Men', 'Spicy Sweet', 'designer', 'Spicy', ARRAY['Grapefruit','Basil','Coriander']::text[], ARRAY['Orange blossom','Cardamom','Ginger']::text[], ARRAY['Amber','Tobacco','Cedar']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.9, 1212, NULL),
    ('parfums-de-marly-kalan', 'Parfums de Marly', 'Kalan', 'Spicy Woody', 'niche', 'Spicy', ARRAY['Blood orange','Spices','Black pepper']::text[], ARRAY['Orange blossom absolute','Lavender','Solar note']::text[], ARRAY['Roasted tonka bean','Amber','Precious woods','Moss','Sandalwood']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.7, 1208, NULL),
    ('amouage-sunshine-man', 'Amouage', 'Sunshine Man', 'Sweet Floral', 'niche', 'Sweet', ARRAY['Lavender','Everlasting flower','Orange brandy']::text[], ARRAY['Clary sage','Juniper berry','Bergamot']::text[], ARRAY['Vanilla','Tonka bean','Cedarwood']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 1149, NULL),
    ('bvlgari-aqva-amara', 'Bvlgari', 'Aqva Amara', 'Aquatic Fresh', 'designer', 'Aquatic', ARRAY['Sicilian mandarin orange','Tunisian neroli']::text[], ARRAY['Aquatic notes','Mineral notes']::text[], ARRAY['Indonesian patchouli','Frankincense']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.9, 1117, NULL),
    ('yves-saint-laurent-kouros', 'Yves Saint Laurent', 'Kouros', 'Animal Spicy', 'designer', 'Musky', ARRAY['Aldehydes','Bergamot','Clary sage','Coriander','Tarragon']::text[], ARRAY['Carnation','Geranium','Jasmine','Orris root','Patchouli','Vetiver','Cinnamon']::text[], ARRAY['Civet','Musk','Oakmoss','Amber','Frankincense','Honey','Leather','Tonka bean','Vanilla']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.6, 1105, NULL),
    ('parfums-de-marly-greenley', 'Parfums de Marly', 'Greenley', 'Fresh Green', 'niche', 'Fresh', ARRAY['Green apple','Sicilian bergamot','Mandarin orange','Cashmere wood']::text[], ARRAY['Pomarose®','Cedarwood','Petitgrain','Violet']::text[], ARRAY['Amberwood','Musk','Oakmoss']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 1095, NULL),
    ('kilian-back-to-black-aphrodisiac', 'Kilian', 'Back to Black, Aphrodisiac', 'Sweet Gourmand', 'niche', 'Sweet', ARRAY['Bergamot','Cardamom','Chamomile','Coriander','Nutmeg','Raspberry']::text[], ARRAY['Honey','Cedarwood','Frankincense','Oakmoss','Patchouli','Vetiver']::text[], ARRAY['Bitter almond','Vanilla absolute','Ambergris','Labdanum']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.9, 1072, NULL),
    ('versace-versace-man-eau-fraiche', 'Versace', 'Versace Man Eau Fraîche', 'Fresh Citrus', 'designer', 'Fresh', ARRAY['Starfruit','Rosewood']::text[], ARRAY['Clary sage','Tarragon','Cedar leaf']::text[], ARRAY['Musk','Amber','Sycamore wood']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.8, 1064, NULL),
    ('tom-ford-grey-vetiver', 'Tom Ford', 'Grey Vetiver', 'Fresh Green', 'designer', 'Fresh', ARRAY['Grapefruit','Orange blossom','Sage','Woods']::text[], ARRAY['Nutmeg','Iris','Pimento']::text[], ARRAY['Vetiver','Oakmoss','Amberwood']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 1047, NULL),
    ('prada-amber-pour-homme', 'Prada', 'Amber pour Homme', 'Powdery Fresh', 'designer', 'Powdery', ARRAY['Cardamom','Neroli','Bergamot','Mandarin orange']::text[], ARRAY['Musk','Orange blossom','Geranium','Myrrh','Vetiver']::text[], ARRAY['Labdanum','Vanilla','Patchouli','Saffron','Sandalwood','Tonka bean','Leather']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 1007, NULL),
    ('xerjoff-casamorati-dolce-amalfi', 'Xerjoff', 'Casamorati - Dolce Amalfi', 'Fruity Spicy', 'niche', 'Fruity', ARRAY['Quince','Apple','Cardamom','Saffron']::text[], ARRAY['Clove','Tolu balm','Frankincense']::text[], ARRAY['Vanilla','Musk','Tonka bean','Amber','Cedarwood']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 1004, NULL),
    ('guerlain-santal-royal', 'Guerlain', 'Santal Royal', 'Woody Oriental', 'designer', 'Woody', ARRAY['Jasmine','Neroli']::text[], ARRAY['Rose','Cinnamon','Peach']::text[], ARRAY['Oud','Leather','Sandalwood','Amber','Musk']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 994, NULL),
    ('creed-himalaya', 'Creed', 'Himalaya', 'Fresh Citrus', 'niche', 'Fresh', ARRAY['Bergamot','Lemon','Mandarin orange']::text[], ARRAY['Juniper berry','Pepper','Jasmine','Lavender','Nutmeg','Gun powder']::text[], ARRAY['Cedarwood','Sandalwood','Tonka bean','Vetiver']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.9, 971, NULL),
    ('xerjoff-casamorati-mefisto', 'Xerjoff', 'Casamorati - Mefisto', 'Citrus Fresh', 'niche', 'Citrus', ARRAY['Bergamot','Grapefruit','Lavender','Calabrian lemon']::text[], ARRAY['Rose absolute','Florentine iris']::text[], ARRAY['Musk','Amber','Cedarwood','Mysore sandalwood']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 956, NULL),
    ('chanel-allure-homme', 'Chanel', 'Allure Homme', 'Woody Spicy', 'designer', 'Woody', ARRAY['Bergamot','Lavender','Peach','Ginger','Lemon','Mandarin orange']::text[], ARRAY['Pepper','Cedar','Freesia','Jasmine','Patchouli','Rosewood','Vetiver','Aniseed','Gardenia','Rose']::text[], ARRAY['Sandalwood','Tonka bean','Amber','Musk','Oakmoss','Vanilla','Benzoin','Coconut','Leather']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 934, NULL),
    ('acqua-di-parma-bergamotto-di-calabria', 'Acqua di Parma', 'Bergamotto di Calabria', 'Citrus Fresh', 'designer', 'Citrus', ARRAY['Lemon','Calabrian bergamot']::text[], ARRAY['Cedarwood','Red ginger']::text[], ARRAY['Musk','Benzoin','Vetiver']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 931, NULL),
    ('yves-saint-laurent-m7-oud-absolu', 'Yves Saint Laurent', 'M7 Oud Absolu', 'Woody Spicy', 'designer', 'Woody', ARRAY['Mandarin orange','Mineral notes','Orange','Bergamot']::text[], ARRAY['Oud','Patchouli','Rosemary']::text[], ARRAY['Labdanum','Myrrh','Amber','Musk','Vetiver']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 925, NULL),
    ('acqua-di-parma-mandorlo-di-sicilia', 'Acqua di Parma', 'Mandorlo di Sicilia', 'Sweet Gourmand', 'designer', 'Sweet', ARRAY['Orange','Star anise','Calabrian bergamot','Italian citrus fruits']::text[], ARRAY['Green almond','Ylang-ylang']::text[], ARRAY['Bourbon vanilla','Musk','Lebanon cedar','Tolu balm']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.8, 912, NULL),
    ('valentino-valentino-uomo', 'Valentino', 'Valentino Uomo', 'Sweet Gourmand', 'designer', 'Sweet', ARRAY['Bergamot','Myrtle']::text[], ARRAY['Gianduja cream','Coffee']::text[], ARRAY['Cedar','White leather']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 876, NULL),
    ('rasasi-daarej-pour-homme', 'Rasasi', 'Daarej pour Homme', 'Sweet Oriental', 'middle-eastern', 'Sweet', ARRAY['Cardamom','Cumin','Mugwort']::text[], ARRAY['Iris','Rose']::text[], ARRAY['Musk','Tonka bean','Vanilla','Amber','Patchouli','Sandalwood']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.8, 873, NULL),
    ('creed-original-vetiver', 'Creed', 'Original Vetiver', 'Green Fresh', 'niche', 'Fresh', ARRAY['Bergamot','Vetiver leaf','Bitter orange','Mandarin orange']::text[], ARRAY['Pink pepper','Coriander','White pepper']::text[], ARRAY['Vetiver','Musk','Ambergris','Sandalwood']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 860, NULL)
)
INSERT INTO fragrances (id, house, name, type, category, scent_family, top_notes, heart_notes, base_notes, attributes, seasons, avg_rating, review_count, bottle_image_url)
SELECT s.id, s.house, s.name, s.type, s.category, s.scent_family, s.top_notes, s.heart_notes, s.base_notes, s.attributes, s.seasons, s.avg_rating, s.review_count, s.bottle_image_url
FROM seed s
WHERE NOT EXISTS (
  SELECT 1 FROM fragrances f
  WHERE lower(f.name) = lower(s.name) AND lower(f.house) = lower(s.house)
);

WITH seed (id, house, name, type, category, scent_family, top_notes, heart_notes, base_notes, attributes, seasons, avg_rating, review_count, bottle_image_url) AS (
  VALUES
    ('guerlain-l-homme-ideal', 'Guerlain', 'L''Homme Idéal', 'Sweet Gourmand', 'designer', 'Sweet', ARRAY['Citrus fruits','Orange blossom','Rosemary']::text[], ARRAY['Almond','Tonka bean']::text[], ARRAY['Cedar','Indian vetiver','Leather']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.7, 852, NULL),
    ('dolce-gabbana-light-blue-pour-homme-forever', 'Dolce & Gabbana', 'Light Blue pour Homme Forever', 'Citrus Fresh', 'designer', 'Citrus', ARRAY['Grapefruit zest','Italian bergamot']::text[], ARRAY['Ozonic notes','Violet leaf']::text[], ARRAY['White musk','Java vetiver','Patchouli']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 849, NULL),
    ('dior-eau-sauvage-parfum', 'Dior', 'Eau Sauvage Parfum', 'Citrus Woody', 'designer', 'Citrus', ARRAY['Calabrian bergamot','Orange']::text[], ARRAY['Lavender absolute','Hedione','Wild flowers']::text[], ARRAY['Philippine elemi','Vetiver','Labdanum','Cinnamon','Star anise']::text[], ARRAY[]::text[], ARRAY[]::text[], 4.2, 830, NULL),
    ('al-haramain-l-aventure', 'Al Haramain', 'L''Aventure', 'Citrus Fresh', 'middle-eastern', 'Citrus', ARRAY['Lemon','Bergamot','Elemi resin']::text[], ARRAY['Lily of the valley','Woody notes','Jasmine']::text[], ARRAY['Amber','Musk','Patchouli']::text[], ARRAY[]::text[], ARRAY[]::text[], 4, 819, NULL),
    ('amouage-lyric-man', 'Amouage', 'Lyric Man', 'Floral Spicy', 'niche', 'Floral', ARRAY['Lime','Bergamot']::text[], ARRAY['Rose','Angelica','Galbanum','Orange blossom','Ginger','Nutmeg','Saffron']::text[], ARRAY['Musk','Pine','Sandalwood','Frankincense','Vanilla']::text[], ARRAY[]::text[], ARRAY[]::text[], 3.9, 807, NULL)
)
INSERT INTO fragrances (id, house, name, type, category, scent_family, top_notes, heart_notes, base_notes, attributes, seasons, avg_rating, review_count, bottle_image_url)
SELECT s.id, s.house, s.name, s.type, s.category, s.scent_family, s.top_notes, s.heart_notes, s.base_notes, s.attributes, s.seasons, s.avg_rating, s.review_count, s.bottle_image_url
FROM seed s
WHERE NOT EXISTS (
  SELECT 1 FROM fragrances f
  WHERE lower(f.name) = lower(s.name) AND lower(f.house) = lower(s.house)
);

-- ============================================================
-- VERIFY AFTER RUNNING
-- ============================================================
-- Total catalog size (expect prior count + the rows added above):
SELECT count(*) AS total_fragrances FROM fragrances;

-- Spot-check the newly added rows by id:
SELECT id, house, name, category, scent_family, avg_rating, review_count
FROM fragrances
WHERE id IN (
  'issey-miyake-l-eau-d-issey-pour-homme',
  'giorgio-armani-emporio-armani-stronger-with-you',
  'giorgio-armani-armani-code-black-code',
  'versace-blue-jeans',
  'dolce-gabbana-the-one-for-men',
  'parfums-de-marly-kalan',
  'amouage-sunshine-man',
  'bvlgari-aqva-amara',
  'yves-saint-laurent-kouros',
  'parfums-de-marly-greenley',
  'kilian-back-to-black-aphrodisiac',
  'versace-versace-man-eau-fraiche',
  'tom-ford-grey-vetiver',
  'prada-amber-pour-homme',
  'xerjoff-casamorati-dolce-amalfi',
  'guerlain-santal-royal',
  'creed-himalaya',
  'xerjoff-casamorati-mefisto',
  'chanel-allure-homme',
  'acqua-di-parma-bergamotto-di-calabria',
  'yves-saint-laurent-m7-oud-absolu',
  'acqua-di-parma-mandorlo-di-sicilia',
  'valentino-valentino-uomo',
  'rasasi-daarej-pour-homme',
  'creed-original-vetiver',
  'guerlain-l-homme-ideal',
  'dolce-gabbana-light-blue-pour-homme-forever',
  'dior-eau-sauvage-parfum',
  'al-haramain-l-aventure',
  'amouage-lyric-man'
)
ORDER BY review_count DESC;
