# gender, release_year, perfumer (None where not reliably publicly documented -
# common for Middle Eastern "clone" houses that don't credit a nose)
METADATA = {
  "acqua-colonia": ("Unisex", 1916, None),
  "acqua-iris": ("Feminine", 2003, None),
  "afnan-9pm": ("Masculine", 2020, None),
  "afnan-supremacy": ("Masculine", 2019, None),
  "ajmal-evoke-silver": ("Masculine", 2016, None),
  "ajmal-shadow": ("Masculine", 2013, None),
  "al-haramain-amber-oud": ("Unisex", 2015, None),
  "amouage-honour-woman-amouage": ("Feminine", 2011, "Pierre Negrin"),
  "amouage-interlude": ("Masculine", 2012, "Karine Vinchon-Spehner"),
  "amouage-lyric-woman-amouage": ("Feminine", 2008, "Pierre Negrin"),
  "amouage-memoir": ("Masculine", 2010, "Pierre Negrin"),
  "amouage-reflection-man-amouage": ("Masculine", 2007, "Richard Herpin"),
  "armaf-club-de-nuit": ("Masculine", 2015, None),
  "armaf-cdni-woman": ("Feminine", 2016, None),
  "armaf-tres-nuit": ("Masculine", 2016, None),
  "armaf-ventana": ("Masculine", 2018, None),
  "bvlgari-man-in-black": ("Masculine", 2014, "Alberto Morillas"),
  "byredo-bal": ("Unisex", 2009, "Jerome Epinette"),
  "byredo-gypsy": ("Unisex", 2008, "Jerome Epinette"),
  "byredo-mojave": ("Unisex", 2014, "Jerome Epinette"),
  "carolina-herrera-good-girl": ("Feminine", 2016, None),
  "cartier-la-panthre-cartier": ("Feminine", 2014, "Mathilde Laurent"),
  "chanel-allure-homme-sport": ("Masculine", 2004, "Jacques Polge"),
  "bleu-chanel": ("Masculine", 2014, "Jacques Polge"),
  "chanel-bleu-de-chanel": ("Masculine", 2010, "Jacques Polge"),
  "chanel-chance-chanel": ("Feminine", 2002, "Jacques Polge"),
  "chanel-chance-eau-tendre": ("Feminine", 2010, "Jacques Polge"),
  "chanel-coco-mademoiselle-chanel": ("Feminine", 2001, "Jacques Polge"),
  "chanel-goste-platinum-chanel": ("Masculine", 1993, "Jacques Polge"),
  "chanel-gabrielle-chanel": ("Feminine", 2017, "Olivier Polge"),
  "chanel-no-19-chanel": ("Feminine", 1970, "Henri Robert"),
  "chanel-no5": ("Feminine", 1921, "Ernest Beaux"),
  "chanel-pour-monsieur-chanel": ("Masculine", 1955, "Henri Robert"),
  "clive-1872": ("Unisex", 1999, None),
  "aventus": ("Masculine", 2010, "Olivier Creed"),
  "creed-aventus-for-her": ("Feminine", 2016, "Olivier Creed"),
  "green-irish": ("Masculine", 1985, "Olivier Creed"),
  "silver-mount": ("Unisex", 1995, "Olivier Creed"),
  "dior-fahrenheit-dior": ("Masculine", 1988, "Jean-Louis Sieuzac"),
  "dior-homme-dior": ("Masculine", 2005, "François Demachy"),
  "homme-intense": ("Masculine", 2011, "François Demachy"),
  "dior-hypnotic-poison-dior": ("Feminine", 1998, "Annick Menardo"),
  "dior-jadore-dior": ("Feminine", 1999, "Calice Becker"),
  "dior-miss-dior-dior": ("Feminine", 1947, "François Demachy"),
  "dior-poison-girl-dior": ("Feminine", 2016, "François Demachy"),
  "sauvage": ("Masculine", 2021, "François Demachy"),
  "diptyque-do": ("Feminine", 2005, "Fabrice Pellegrin"),
  "diptyque-philosykos-diptyque": ("Unisex", 1996, "Olivia Giacobetti"),
  "diptyque-tam": ("Unisex", 2003, "Fabrice Pellegrin"),
  "dolce-gabbana-light-blue": ("Feminine", 2001, None),
  "dolce-gabbana-the-one": ("Feminine", 2006, None),
  "este-lauder-beautiful-este": ("Feminine", 1985, "Sophia Grojsman"),
  "este-lauder-pleasures-este": ("Feminine", 1995, "Sophia Grojsman"),
  "fragrance-world-baroque": ("Unisex", None, None),
  "carnal-flower": ("Feminine", 2005, "Dominique Ropion"),
  "portrait-lady": ("Feminine", 2010, "Dominique Ropion"),
  "giorgio-armani-acqua-di": ("Masculine", 1996, "Alberto Morillas"),
  "armani-acquagio": ("Masculine", 2015, "Alberto Morillas"),
  "giorgio-armani-si-giorgio": ("Feminine", 2013, "Loc Dong"),
  "givenchy-gentleman": ("Masculine", 2017, None),
  "givenchy-irresistible-givenchy": ("Feminine", 2019, None),
  "givenchy-linterdit-givenchy": ("Feminine", 2018, None),
  "givenchy-pi-givenchy": ("Masculine", 1998, None),
  "guerlain-habit": ("Masculine", 1965, "Jean-Paul Guerlain"),
  "guerlain-mitsouko-guerlain": ("Feminine", 1919, "Jacques Guerlain"),
  "guerlain-mon-guerlain-guerlain": ("Feminine", 2017, "Thierry Wasser"),
  "guerlain-shalimar": ("Feminine", 1925, "Jacques Guerlain"),
  "guerlain-shalimar-souffle-guerlain": ("Feminine", 2018, "Thierry Wasser"),
  "guerlain-vetiver-guerlain": ("Masculine", 1959, "Jean-Paul Guerlain"),
  "herms-jour-dherms-herms": ("Feminine", 2013, "Jean-Claude Ellena"),
  "hermes-terre": ("Masculine", 2006, "Jean-Claude Ellena"),
  "herms-twilly-dherms-herms": ("Feminine", 2017, "Christine Nagel"),
  "hermes-jardin": ("Unisex", 2005, "Jean-Claude Ellena"),
  "initio-atomic": ("Unisex", 2019, None),
  "initio-oud": ("Unisex", 2016, None),
  "issey-miyake-leau-dissey": ("Feminine", 1992, "Jacques Cavallier"),
  "jean-paul-gaultier-classique": ("Feminine", 1993, "Jacques Cavallier"),
  "kenzo-flower-by-kenzo": ("Feminine", 2000, "Alberto Morillas"),
  "kilian-black": ("Unisex", 2016, "Sidonie Lancesseur"),
  "kilian-love": ("Feminine", 2007, "Calice Becker"),
  "lancme-la-vie-est": ("Feminine", 2012, "Dominique Ropion"),
  "lancme-trsor-lancme": ("Feminine", 1990, "Sophia Grojsman"),
  "lanvin-arpge-lanvin": ("Feminine", 1927, "André Fraysse"),
  "lattafa-asad": ("Masculine", 2020, None),
  "lattafa-badee-al-oud": ("Unisex", 2021, None),
  "lattafa-khamrah": ("Unisex", 2022, None),
  "lattafa-najdia": ("Unisex", 2022, None),
  "lattafa-oud-for-glory": ("Masculine", 2022, None),
  "lattafa-oud-mood": ("Unisex", 2021, None),
  "lattafa-raghba": ("Unisex", 2021, None),
  "lattafa-yara": ("Feminine", 2021, None),
  "le-labo-another-13": ("Unisex", 2007, "Frank Voelkl"),
  "rose-31": ("Unisex", 2006, "Daphne Bugey"),
  "santal": ("Unisex", 2011, "Frank Voelkl"),
  "the-noir": ("Unisex", 2006, "Frank Voelkl"),
  "baccarat": ("Unisex", 2015, "Francis Kurkdjian"),
  "grand-soir": ("Unisex", 2016, "Francis Kurkdjian"),
  "margiela-beach": ("Unisex", 2014, "Jacques Cavallier"),
  "maison-margiela-replica-by": ("Unisex", 2014, "Jacques Cavallier"),
  "replica-jazz": ("Masculine", 2013, "Jacques Cavallier"),
  "margiela-lazy": ("Unisex", 2014, "Jacques Cavallier"),
  "marc-jacobs-daisy-marc": ("Feminine", 2007, None),
  "memo-paris-irish-leather": ("Unisex", 2007, "Aliénor Massenet"),
  "montale-intense": ("Unisex", 2010, None),
  "nina-ricci-lair-du": ("Feminine", 1948, None),
  "orientica-amber-rouge": ("Unisex", None, None),
  "orientica-velvet-oud": ("Unisex", None, None),
  "paco-million": ("Masculine", 2008, None),
  "paco-rabanne-lady-million": ("Feminine", 2010, None),
  "paco-rabanne-olympa-paco": ("Feminine", 2015, None),
  "herod": ("Masculine", 2017, None),
  "layton": ("Masculine", 2016, None),
  "pegasus": ("Masculine", 2018, None),
  "penhaligons-endymion-penhaligons": ("Masculine", 2013, None),
  "penhaligons-halfeti": ("Unisex", 2016, None),
  "prada-candy-prada": ("Feminine", 2011, "Daniela Andrier"),
  "prada-infusion-diris-prada": ("Feminine", 2007, "Daniela Andrier"),
  "prada-lhomme-prada": ("Masculine", 2016, "Daniela Andrier"),
  "prada-luna-rossa-ocean": ("Masculine", 2021, "Daniela Andrier"),
  "rasasi-dhan-al-oudh": ("Unisex", None, None),
  "rasasi-hawas": ("Masculine", 2018, None),
  "rasasi-la-yuqawam": ("Masculine", 2015, None),
  "roja-dove-enigma-roja": ("Masculine", None, "Roja Dove"),
  "roja-danger": ("Masculine", 2013, "Roja Dove"),
  "roja-elysium": ("Masculine", 2013, "Roja Dove"),
  "serge-ambre": ("Unisex", 2000, "Serge Lutens"),
  "serge-daim": ("Unisex", 2004, "Serge Lutens"),
  "swiss-arabian-shaghaf": ("Unisex", None, None),
  "swiss-arabian-wajd": ("Unisex", None, None),
  "thierry-mugler-alien-thierry": ("Feminine", 2005, "Dominique Ropion"),
  "thierry-mugler-angel-thierry": ("Feminine", 1992, "Olivier Cresp"),
  "black-orchid": ("Unisex", 2006, "David Apel"),
  "lost-cherry": ("Unisex", 2018, "Yann Vasnier"),
  "neroli": ("Masculine", 2011, "Rodrigo Flores-Roux"),
  "oud-wood": ("Unisex", 2007, "Richard Herpin"),
  "rose-prick": ("Unisex", 2018, "Nathalie Lorson"),
  "tobacco-oud": ("Unisex", 2019, None),
  "valentino-donna-born-in": ("Feminine", 2019, None),
  "valentino-uomo-born-in": ("Masculine", 2019, None),
  "uomo-intense": ("Masculine", 2015, None),
  "valentino-valentina-valentino": ("Feminine", 2011, None),
  "versace-bright-crystal-versace": ("Feminine", 2004, "Alberto Morillas"),
  "versace-eros-versace": ("Masculine", 2012, "Aurelien Guichard"),
  "viktor-rolf-flowerbomb-viktor": ("Feminine", 2005, "Olivier Polge"),
  "xerjoff-casamorati-1888-xerjoff": ("Unisex", 2013, None),
  "xerjoff-naxos": ("Masculine", 2013, None),
  "yves-saint-laurent-black": ("Feminine", 2014, "Nathalie Lorson"),
  "ysl-lanuit": ("Masculine", 2009, "Anne Flipo"),
  "yves-saint-laurent-libre": ("Feminine", 2019, "Anne Flipo"),
  "ysl-myslf": ("Masculine", 2023, "Anne Flipo"),
  "yves-saint-laurent-opium": ("Feminine", 1977, "Jean-Louis Sieuzac"),
}
